/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WeightedMedianData {
  weight: number
  value: number
}
export function weightedMedian(data: Array<WeightedMedianData>): number | null
